#+TITLE: Living Language Russian - Essential
#+AUTHOR: DJJazzyBrett
#+EMAIL: mmoc.liamg.ta@gmail.com

* LESSON 1

** Vocabulary Builder 1

- здравствуйте

- здравствуй

- привет

- господин

- госпожа

- Очень приятно!

- бизнесмен

- журналист

- журналистка

- американец

- американка

- Добро пожаловать!

- До свидания!

- Спасибо.

** Grammar Builder 1

- Я (I)

- ты (you ... informal)

- он (he or it ... masculine)

- она (she or it ... feminine)

- оно (it ... neuter)

- вы (you ... singular; formal)

** Vocabulary Builder 2

- Как дела?

- Хорошо.

- Вы говорите по-русски?

- Да.

- Нет.

- Немного.

- господа

- Я американец.

- Я американка.

- Я студент.

- Я студентка.

- Извини.

- Извините.

- Пойдём!

- Пойдёмте!

- Пожалуйста!

** Grammar Builder 2

- мы (we)

- вы (you ... plural)

- они (they)

* LESSON 2

** Vocabulary Builder 1

- семья

- мать; мама

- отец; папа

- сын

- дочь; дочка

- брат

- сестра

- бабушка

- дедушка

- родители

- дети

**  Grammar Builder 1

*Distinguishing Masculine & Feminine Nouns*

All Russian nouns have gender. The gender of the nouns for human beings is obvious - those referring to males are masculine, to females, feminine. The gender of nouns referring to inanimate objects is determined by their endings.

As a rule, masculine nouns end in a consonant, for example, отец, брат; however, there's a significant group of masculine nouns that end in an *а* or *я*, such as папа and дедушка.

Most feminine nouns end in a vowel *а* or *я*, such as семья, мама, бабушка; however, there's a group of feminine nouns that end in the soft sign, for example, мать. We'll sometimes refer to these as "the soft sign feminines."

** Vocabulary Builder 2

- мальчик

- девочка

- молодой человек

- девушка

- друг

- подруга

- муж

- жена

- мой

- моя

- мои

- Это ...

- мужчина

- женщина

** Grammar Builder 2

*Introducing People or Things With Это*

When you first introduce a person - or show a thing - you use a construction that is simpler in Russian than it is in English. All you do is this: you just say *Это* and then mention the person or thing you are introducing.

- Это мой друг.

- Это мои дети.

- Это моя жена.

- Это Джон.

Notice that unlike English the Russian demonstrative pronoun *это* always stays the same whether it introduces a singular or plural noun; and the verb /to be/,as you may recall, is omitted in the present tense in Russian.

When you want to refer to someone or something mentioned earlier, you use one of the regular pronouns *он, она, оно, они* depending on the gender and number of the noun you are referring to by the pronoun.

- Это Джон. Он мой друг.

- Это моя дочь. Она студентка.

You can easily turn the above statements into questions just by raising your intonation. For example,

- Это Джон?

- Да, это Джон.

* LESSON 3

** Vocabulary Builder 1

- один

- одна

- одно

- одни

- оно

- стол

- стул

- дом

- квартира

- комната

- вещь

- вино

- окно

- письмо

- море

** Grammar Builder 1

The numeral /one/ has gender in Russian, which means that it matches the gender of the nouns it modifies. For example, if it's modifying a masculine noun, it's in the masculine form.

- один американец

- один стул

If it's modifying a feminine noun, it's in the feminine form.

- одна вещь

- одна квартира

If it's modifying a neuter noun, it's neuter.

- одно письмо

- одно окно

In the plural form, *одни* means /alone/ or /nobody but/. For example,

- одни дети

- одни родители

However, if you switch around the numeral /one/ and the noun it modifies, then the phrase also changes its meaning to /"X is one (alone)"/ or /"XX are alone."/ For example,

- Мой сын один.

- Моя дочь одна.

- Мои родители одни.

** Vocabulary Builder 2
